FROM oven/bun:1
WORKDIR /app

RUN apt-get update && apt-get install -y ffmpeg

COPY package.json bun.lockb* ./

RUN bun install

COPY . .

RUN bunx prisma generate

EXPOSE 3000

CMD [ "bun", "--watch", "server.ts"]